# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: gitsubmodule
    rebase-strategy: 'auto'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'

  - package-ecosystem: npm
    rebase-strategy: 'auto'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 1
    versioning-strategy: increase
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
    groups:
      development-dependencies:
        dependency-type: 'development'
    ignore:
      - dependency-name: '*'
        versions: ['version-update:semver-major']
      - dependency-name: 'typescript' # This is likely to conflict with peer dependencies and stop the whole dependency update process
        versions: ['*']
